### ISSUE TITLE
npx miniflare execute fail

### ISSUE THREAD

**Issue by akinazuki** [cloudflare/wrangler2#1096]
## What version of Wrangler are you using?
2.4.0

## What operating system are you using?
macOS 12.4 (21F79)

## Describe the Bug
I'm trying to use ```r2_buckets``` in wrangler2,  but i'm not sure where is wrong in my ```wrangler.toml``` 

Here is my configuration file (copy from https://developers.cloudflare.com/workers/wrangler/configuration/)

```
name = "storage"
#route = ''
#zone_id = ''
#usage_model = ''
#compatibility_flags = ["r2_public_beta_bindings"]
workers_dev = true
compatibility_date = "2022-05-19"
account_id = ""


[vars]

r2_buckets = [{
	binding = "MY_BUCKET",
 	bucket_name = "storage",
	preview_bucket_name = "storage"
}]
```

I got this error when i'm executing ```npx miniflare```
```
➜  r2-api git:(main) ✗ npx miniflare
[mf:err] TomlError: Unterminated inline array at row 16, col 16, pos 303:
15: 
16> r2_buckets = [{
                   ^
17:     binding = "MY_BUCKET",


    at TOMLParser.parseInlineTable (/usr/local/lib/node_modules/miniflare/node_modules/@iarna/toml/lib/toml-parser.js:1337:26)
    at TOMLParser.runOne (/usr/local/lib/node_modules/miniflare/node_modules/@iarna/toml/lib/parser.js:64:30)
    at TOMLParser.parse (/usr/local/lib/node_modules/miniflare/node_modules/@iarna/toml/lib/parser.js:45:22)
    at Object.parseString [as parse] (/usr/local/lib/node_modules/miniflare/node_modules/@iarna/toml/parse-string.js:13:12)
    at EventTarget.#init (/usr/local/lib/node_modules/miniflare/node_modules/@miniflare/core/src/index.ts:340:45)
    at EventTarget.getPlugins (/usr/local/lib/node_modules/miniflare/node_modules/@miniflare/core/src/index.ts:970:5)
    at createServer (/usr/local/lib/node_modules/miniflare/node_modules/@miniflare/http-server/src/index.ts:334:19)
    at startServer (/usr/local/lib/node_modules/miniflare/node_modules/@miniflare/http-server/src/index.ts:420:18)
    at main (/usr/local/lib/node_modules/miniflare/src/cli.ts:96:5)
```

**Comment by petebacondarwin** [comment]
Hi @akinazuki - sorry about this but the docs are a bit misleading. In TOML you cannot have an "inline" object that spans multiple lines. The correct format should be:

```toml
r2_buckets = [{ binding = "MY_BUCKET", bucket_name = "storage", preview_bucket_name = "storage" }]
```
