### ISSUE TITLE
Error on remote worker: TypeError: fetch failed

### ISSUE THREAD

**Issue by Penggeor** [cloudflare/wrangler2#1179]
I am comply with the [Cloudflare Worker Get started guide](https://developers.cloudflare.com/workers/get-started/guide/)，and I got the this weird error：
```
➜  Invoke-SendGrid-Worker git:(main) ✗ npx wrangler dev
 ⛅️ wrangler 2.0.7
-------------------
⬣ Listening at http://localhost:8787
✘ [ERROR] Error on remote worker: TypeError: fetch failed

      at Object.processResponse
  (/Users/pandy/Desktop/worker/Tester/Invoke-SendGrid-Worker/node_modules/wrangler/wrangler-dist/cli.js:73952:34)
      at
  /Users/pandy/Desktop/worker/Tester/Invoke-SendGrid-Worker/node_modules/wrangler/wrangler-dist/cli.js:74274:42
      at node:internal/process/task_queues:141:7
      at AsyncResource.runInAsyncScope (node:async_hooks:202:9)
      at AsyncResource.runMicrotask (node:internal/process/task_queues:138:8)
      at processTicksAndRejections (node:internal/process/task_queues:96:5) {
    cause: ConnectTimeoutError: Connect Timeout Error
        at Timeout.onConnectTimeout [as _onTimeout]
  (/Users/pandy/Desktop/worker/Tester/Invoke-SendGrid-Worker/node_modules/wrangler/wrangler-dist/cli.js:68445:28)
        at listOnTimeout (node:internal/timers:561:11)
        at processTimers (node:internal/timers:502:7) {
      code: 'UND_ERR_CONNECT_TIMEOUT'
    }
  }
```

**Comment by Penggeor** [comment]
@bretthoerner @jkriss @tomdee @bwesterb

**Comment by threepointone** [comment]
That's an odd error "UND_ERR_CONNECT_TIMEOUT". Does it do this every time? Do you have a corporate proxy or something on your machine? Could you also try starting it with `--local` and tell me if the problem persists?

**Comment by Penggeor** [comment]
@threepointone The problem has been solved when I add `--local`.I have some other problems:
1. Why do I have to use the `--local` flag? The doc [6. Preview your project](https://developers.cloudflare.com/workers/get-started/guide/#6-preview-your-project) has didn't mention about.
2. The docs and tutorial video is stale for the latest `wrangler` CLI. I am a frontend developer and new to Cloudflare Worker, which was so frustrating for me.

**Comment by threepointone** [comment]
`--local` is a workaround for you for now, it runs your worker in a local simulation environment (as opposed to the default 'remote' mode which runs on the actual cloudflare edge and is proxied through localhost); it shouldn't be required! 

- Could you tell me whether you have a corporate proxy on your machine? If you run `echo $HTTP_PROXY && echo $HTTPS_PROXY && echo $http_proxy && echo $https_proxy` in your terminal, do you see anything?

**Comment by Penggeor** [comment]
@threepointone Nothing output:
<img width="604" alt="image" src="https://user-images.githubusercontent.com/68799055/171995290-451b52eb-4d08-4a2d-8d46-3dc6165697f8.png">

**Comment by Penggeor** [comment]
@threepointone Nothing output:
<img width="570" alt="image" src="https://user-images.githubusercontent.com/68799055/171995344-18eb37ae-db70-453c-8b52-aee6fcf2737e.png">

**Comment by threepointone** [comment]
Hmm ok so we can rule that out. This is a weird error, I'll have to have a look when I'm back at my laptop next week. Sorry for this experience! I hope the --local workaround should hold you till then.

**Comment by Penggeor** [comment]
Thank my friend @threepointone. Another question emerges, and I guess it comes from the same problem. I am waiting for your replay.

I add some code:
```js
    const { headers } = request;
    const contentType = headers.get('content-type') || '';
    if (contentType.includes('form')) {
      const formData = await request.formData();
    }
```

Error
```bash
[mf:err] Unhandled Promise Rejection: TypeError: Invalid state: ReadableStream is locked
    at new NodeError (node:internal/errors:372:5)
    at setupReadableStreamDefaultReader (node:internal/webstreams/readablestream:1787:11)
    at new ReadableStreamDefaultReader (node:internal/webstreams/readablestream:773:5)
    at ReadableStream.values (node:internal/webstreams/readablestream:427:20)
    at /Users/pandy/Desktop/worker/heighliner-website-worker/Invoke-SendGrid-Worker/node_modules/@miniflare/core/src/standards/http.ts:341:52
    at new Promise (<anonymous>)
    at Request.formData (/Users/pandy/Desktop/worker/heighliner-website-worker/Invoke-SendGrid-Worker/node_modules/@miniflare/core/src/standards/http.ts:313:11)
    at Object.fetch (/private/Users/pandy/Desktop/worker/heighliner-website-worker/Invoke-SendGrid-Worker/src/index.ts:48:38)
```

**Comment by threepointone** [comment]
I don't think this is related to the original problem, seems more like an actual coding problem. I can't say without looking at the actual code, but it probably has to do with how you're reading data from the request. I'm not sure. I think questions like that are more suitable with a community resource like the discord https://discord.com/invite/cloudflaredev or stackoverflow.

**Comment by Penggeor** [comment]
Have any conclusion about the question？ @threepointone

**Comment by petebacondarwin** [comment]
Hi @Penggeor - there appears to be two problems here:

1. The requests to the Cloudflare API are timing out when trying to run `wrangler dev` (not in local mode).
2. There is a problem, even in local mode, where you are unable to read form data from the headers

This issue should focus on the first problem. In order to solve it we need to be able to reproduce the problem. Could you create a reproduction project that you can share with us, so that we can see exactly what the setup is? This should be as minimal as possible - remove as much code and configuration from the project while still demonstrating the problem.

The second problem could be a problem with your code, but it is not possible to tell without a reproduction. Please could you open up a second issue with a reproduction of that error - again having removed as much code and configuration as possible.

Once we have these reproductions, we can try to dig into what the causes are.
