### ISSUE TITLE
🐛 BUG: 413 Request Entity Too Large

### ISSUE THREAD

**Issue by samhamilton** [cloudflare/wrangler2#1280]
### What version of `Wrangler` are you using?

2.0.12

### What operating system are you using?

Linux

### Describe the Bug

Running `wrangler publish --env prod` gives me 

```
2022-06-16T11:54:29.7238769Z [31m✘ [41;31m[[41;97mERROR[41;31m][0m [1mReceived a malformed response from the API[0m
2022-06-16T11:54:29.7247026Z 
2022-06-16T11:54:29.7247203Z   <html>
2022-06-16T11:54:29.7247604Z   <head><title>413 Request Entity Too Large</title></head>
2022-06-16T11:54:29.7248010Z   <body>
2022-06-16T11:54:29.7248490Z   <center><h1>413 Request En... (length = 184)
2022-06-16T11:54:29.7248854Z 
2022-06-16T11:54:29.7249557Z   PUT /accounts/*******/storage/kv/namespaces/*******/bulk -> 413 Payload Too Large
```

**Comment by threepointone** [comment]
Are you using workers sites? Could you tell me what the size of your assets folder is?

**Comment by threepointone** [comment]
We thought we'd fixed this in https://github.com/cloudflare/wrangler2/pull/1195 / 2.0.11, so I guess we might have to revisit that. Did you previously have this working in wrangler 1? Or is this a new project? Further question, did you try running wrangler dev on this project?

**Comment by samhamilton** [comment]
Yes it used to work but when trying deploy this week I got the following error:
 ```
Error: Something went wrong with the request to Cloudflare...
workers.api.error.script_too_large [API code: 10027]
```
so tried to upgrade to see if that would work around the problem.

`wangler dev` gives this error:
```
✘ [ERROR] Error on remote worker: ParseError: Received a malformed response from the API

      at fetchInternal (/opt/homebrew/lib/node_modules/wrangler/wrangler-dist/cli.js:117995:11)
      at processTicksAndRejections (node:internal/process/task_queues:96:5)
      at async fetchResult (/opt/homebrew/lib/node_modules/wrangler/wrangler-dist/cli.js:118050:16)
      at async putKVBulkKeyValue
  (/opt/homebrew/lib/node_modules/wrangler/wrangler-dist/cli.js:120907:5)
      at async Promise.all (index 7)
      at async syncAssets (/opt/homebrew/lib/node_modules/wrangler/wrangler-dist/cli.js:121084:3)
      at async start (/opt/homebrew/lib/node_modules/wrangler/wrangler-dist/cli.js:121186:22) {
    text: 'Received a malformed response from the API',
    notes: [
      {
        text: '<html>\r\n' +
          '<head><title>413 Request Entity Too Large</title></head>\r\n' +
          '<body>\r\n' +
          '<center><h1>413 Request En... (length = 184)'
      },
      {
        text: 'PUT
  /accounts/******/storage/kv/namespaces/******/bulk
  -> 413 Payload Too Large'
      }
    ],
    location: undefined,
    kind: 'error'
  }

**Comment by threepointone** [comment]
Could you try this with `wrangler@beta` and see if that solves your issue?

**Comment by samhamilton** [comment]
@threepointone yep looks good so far 
`↗️  Done syncing assets`

**Comment by threepointone** [comment]
Very good, looks like we fixed it in https://github.com/cloudflare/wrangler2/pull/1392. I'll close this issue. We'll do a release later today, so it'll be more widely available. Thanks for filing!
