### ISSUE TITLE
🐛 BUG: [pages:err] RangeError: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by jazoom** [cloudflare/wrangler2#1462]
### What version of `Wrangler` are you using?

0.0.0-d35c69f

### What operating system are you using?

Linux

### Describe the Bug

A project that was working suddenly became not working after installing wrangler@d1. The only way to get it working again seems to be to revert to v2.0.15 after blowing away `node_modules`.

```
[pages:err] RangeError: Maximum call stack size exceeded
    at Object.getRequestContext (/project/node_modules/@miniflare/shared/src/index.ts:1:1)
    at Object.get [as getRequestContext] (/project/node_modules/@miniflare/core/dist/src/index.js:18:52)
    at Function.requestContextNow (/project/node_modules/@miniflare/core/src/standards/date.ts:5:10)
    at Function.requestContextNow (/project/node_modules/@miniflare/core/src/standards/date.ts:5:51)
    at Function.requestContextNow (/project/node_modules/@miniflare/core/src/standards/date.ts:5:51)
    at Function.requestContextNow (/project/node_modules/@miniflare/core/src/standards/date.ts:5:51)
    at Function.requestContextNow (/project/node_modules/@miniflare/core/src/standards/date.ts:5:51)
    at Function.requestContextNow (/project/node_modules/@miniflare/core/src/standards/date.ts:5:51)
    at Function.requestContextNow (/project/node_modules/@miniflare/core/src/standards/date.ts:5:51)
    at Function.requestContextNow (/project/node_modules/@miniflare/core/src/standards/date.ts:5:51)
```

The run command: `"BROWSER=none wrangler pages dev --port 8788 ."`

As you can imagine, debugging this is difficult. I was able to determine that removing the following line made it start:
`import { pick } from 'lodash-es';`

I then put in my own version of `pick` (https://github.com/you-dont-need/You-Dont-Need-Lodash-Underscore#_pick) and it started crashing again.
```
function pick(object, keys) {
  return keys.reduce((obj, key) => {
     if (object && object.hasOwnProperty(key)) {
        obj[key] = object[key];
     }
     return obj;
   }, {});
}
```

Removing that completely seemed to work but then when I tried to call any of the functions I got more of those same errors.

I don't know what the cause is. This file doesn't even exist: `/project/node_modules/@miniflare/shared/src/index.ts:1:1`. Instead, there is `/project/node_modules/@miniflare/shared/dist/src/index.d.ts`.

**Comment by sidharthachatterjee** [comment]
Thanks for reporting this! This is odd for sure. 

I'll defer to the D1 team on this, paging @geelen 🙏🏼

**Comment by jazoom** [comment]
@sidharthachatterjee This isn't a D1 issue. I just removed node_modules and yarn.lock and confirmed that the problem isn't there with `"wrangler": "^2.0.15"` but it is with `"wrangler": "^2.0.22"`.

**Comment by jazoom** [comment]
Actually, to be more specific, when I use the yarn.lock that was in source control at the time I was on wrangler 2.0.15 then there is no problem, but if I use the same package.json file from then and do a fresh `yarn install` of wrangler 2.0.15 then the issue presents itself. I guess this means one of your dependencies that isn't fixed to a certain version had an update that is causing this issue.

**Comment by jazoom** [comment]
And the issue linked by @WalshyDev suggests that dependency would be Miniflare

**Comment by GregBrimble** [comment]
I think we'll track this over at https://github.com/cloudflare/miniflare/issues/314. Once this gets fixed and released in Miniflare, we're pretty quick to bump versions in wrangler, so it'll be fixed here shortly afterwards.
