### ISSUE TITLE
🐛 BUG: Error while creating remote dev session: TypeError: fetch failed  

### ISSUE THREAD

**Issue by tianluanchen** [cloudflare/wrangler2#1489]
### What version of `Wrangler` are you using?

2.0.22

### What operating system are you using?

Windows

### Describe the Bug

I constructed the project using the wrangler init command and authorized my account, then I got the following error when executing wrangler dev
```powershell
⬣ Listening at http://localhost:8787
X [ERROR] Error while creating remote dev session: TypeError: fetch failed      

      at Object.processResponse
  (C:\Users\workspace\f\node_modules\wrangler\wrangler-dist\cli.js:74624:34)
      at C:\Users\workspace\f\node_modules\wrangler\wrangler-dist\cli.js:74946:42
      at processTicksAndRejections (node:internal/process/task_queues:96:5) {   
    cause: ConnectTimeoutError: Connect Timeout Error
        at Timeout.onConnectTimeout [as _onTimeout]
  (C:\Users\workspace\f\node_modules\wrangler\wrangler-dist\cli.js:69093:28)
        at listOnTimeout (node:internal/timers:561:11)
        at processTimers (node:internal/timers:502:7) {
      code: 'UND_ERR_CONNECT_TIMEOUT'
    }
  }
```
I also tried to configure the proxy and set the environment variables, but it didn't work
```powershell
$env:HTTP_PROXY="http://localhost:10809"

 ⛅️ wrangler 2.0.22 
--------------------
Retrieving cached values for userId from node_modules\.cache\wrangler
⬣ Listening at http://localhost:8787
X [ERROR] Error while creating remote dev session: TypeError: fetch failed      

      at Object.processResponse
  (C:\Users\workspace\f\node_modules\wrangler\wrangler-dist\cli.js:74624:34)
      at C:\Users\workspace\f\node_modules\wrangler\wrangler-dist\cli.js:74946:42
      at node:internal/process/task_queues:141:7
      at AsyncResource.runInAsyncScope (node:async_hooks:202:9)
      at processTicksAndRejections (node:internal/process/task_queues:96:5) {
    cause: [Error: 13080:error:1408F10B:SSL routines:ssl3_get_record:wrong version
  number:c:\ws\deps\openssl\openssl\ssl\record\ssl3_record.c:332:
    ] {
      library: 'SSL routines',
      function: 'ssl3_get_record',
      reason: 'wrong version number',
      code: 'ERR_SSL_WRONG_VERSION_NUMBER'
    }
```

**Comment by isaac-mcfadyen** [comment]
Are you perhaps using Cloudflare WARP or another proxy/VPN that does TLS inspection?

**Comment by tianluanchen** [comment]
> Are you perhaps using Cloudflare WARP or another proxy/VPN that does TLS inspection?

Thanks. I have found a solution

**Comment by ResetPower** [comment]
> > Are you perhaps using Cloudflare WARP or another proxy/VPN that does TLS inspection?
> 
> Thanks. I have found a solution

I wonder what your solution is. Could you tell me? I met the same problem.

**Comment by tianluanchen** [comment]
> > > Are you perhaps using Cloudflare WARP or another proxy/VPN that does TLS inspection?
> > 
> > 
> > Thanks. I have found a solution
> 
> I wonder what your solution is. Could you tell me? I met the same problem.

I set up the system proxy, and then executed it several times, and it was successful once in a while
