### ISSUE TITLE
🐛 BUG: wrangler tail crashes when encountering a log from a Durable Object alarm invocation

### ISSUE THREAD

**Issue by a-robinson** [cloudflare/wrangler2#1519]
### What version of `Wrangler` are you using?

2.0.22

### What operating system are you using?

Linux (also happens on Mac)

### Describe the Bug

Wrangler tail crashes if it gets sent a log from a DO alarm invocation. To repro:

1. Deploy a DO that uses alarms, such as the example from https://blog.cloudflare.com/durable-objects-alarms/
2. Start a wrangler tail session on that script
3. Send a request to a DO that will cause an alarm to be run in the near future
4. When the alarm finally runs, wrangler tail will print an error and exit.

The error I've been getting is:

```
/home/arobinson/.npm/_npx/32026684e21afda6/node_modules/wrangler/wrangler-dist/cli.js:16907
            throw ex;
            ^

TypeError: Cannot read properties of undefined (reading 'method')
    at WebSocket3.prettyPrintLogs (/home/arobinson/.npm/_npx/32026684e21afda6/node_modules/wrangler/wrangler-dist/cli.js:127428:54)
    at WebSocket3.emit (node:events:527:28)
    at Receiver2.receiverOnMessage (/home/arobinson/.npm/_npx/32026684e21afda6/node_modules/wrangler/wrangler-dist/cli.js:85301:24)
    at Receiver2.emit (node:events:527:28)
    at Receiver2.dataMessage (/home/arobinson/.npm/_npx/32026684e21afda6/node_modules/wrangler/wrangler-dist/cli.js:84002:18)
    at Receiver2.getData (/home/arobinson/.npm/_npx/32026684e21afda6/node_modules/wrangler/wrangler-dist/cli.js:83965:21)
    at Receiver2.startLoop (/home/arobinson/.npm/_npx/32026684e21afda6/node_modules/wrangler/wrangler-dist/cli.js:83820:27)
    at Receiver2._write (/home/arobinson/.npm/_npx/32026684e21afda6/node_modules/wrangler/wrangler-dist/cli.js:83777:14)
    at writeOrBuffer (node:internal/streams/writable:389:12)
    at _write (node:internal/streams/writable:330:10)
```

@xortive has pointed out that https://github.com/cloudflare/wrangler2/blob/main/packages/wrangler/src/tail/printing.ts "seems to assume all non-scheduled events are http and pukes when trying to pull the request method out"

**Comment by threepointone** [comment]
related: https://github.com/cloudflare/wrangler2/issues/1200

**Comment by caass** [comment]
Does this fail when using `--json` (or `--format json`, I can't remember what the usage is)? If not, can you provide an example of an alarm event in JSON formatting?

**Comment by a-robinson** [comment]
It does not fail when using `--json`. Here's an example:
```
{
  "outcome": "ok",
  "scriptName": "my-worker-name-here",
  "exceptions": [],
  "logs": [
    {
      "message": [
        "my message here"
      ],
      "level": "log",
      "timestamp": 1658843798477
    }
  ],
  "eventTimestamp": 1658843798474,
  "event": {
    "scheduledTime": "2022-07-26T13:56:38.473Z"
  }
}
```

**Comment by caass** [comment]
@a-robinson this should be fixed now, feel free to re-open if not!

**Comment by a-robinson** [comment]
Thanks @caass ! Is there an easy way to test prior to #1594 making it out or should I just wait?

**Comment by caass** [comment]
> Thanks @caass ! Is there an easy way to test prior to #1594 making it out or should I just wait?

Try using the `beta` tag, e.g. `wrangler@beta`. It should contain this PR :)

**Comment by a-robinson** [comment]
Perfect, works great!

```
Alarm @ 8/1/2022, 3:58:43 PM - Ok
  (log) [...]
```
