### ISSUE TITLE
🐛 BUG: `UND_ERR_SOCKET` when trying `pages dev` with Durable Objects via WebSocket

### ISSUE THREAD

**Issue by awthwathje** [cloudflare/wrangler2#1697]
### What version of `Wrangler` are you using?

https://prerelease-registry.developers.workers.dev/runs/2842829360/npm-package-wrangler-1665

### What operating system are you using?

Linux

### Describe the Bug

Reproduction repo: https://github.com/awthwathje/remix-cf-pages-durable-objects-websocket-debug

This is concerning new functionality of `pages dev` making it possible to bind Durable Objects. It seems there is a problem with initiating a WebSocket connection to a Durable Object: it does error with the following:

```
TypeError: fetch failed

at Object.processResponse (/home/node/projects/remix-cf-pages-durable-objects-websocket-debug/node_modules/undici/lib/fetch/index.js:198:23)
    at /home/node/projects/remix-cf-pages-durable-objects-websocket-debug/node_modules/undici/lib/fetch/index.js:929:38
    at node:internal/process/task_queues:140:7
    at AsyncResource.runInAsyncScope (node:async_hooks:203:9)
    at AsyncResource.runMicrotask (node:internal/process/task_queues:137:8) {
  cause: SocketError: other side closed
      at Socket.onSocketEnd (/home/node/projects/remix-cf-pages-durable-objects-websocket-debug/node_modules/undici/lib/client.js:958:22)
      at Socket.emit (node:events:549:35)
      at Socket.emit (node:domain:482:12)
      at endReadableNT (node:internal/streams/readable:1359:12)
      at processTicksAndRejections (node:internal/process/task_queues:82:21) {
    code: 'UND_ERR_SOCKET',
    socket: {
      localAddress: '127.0.0.1',
      localPort: 54674,
      remoteAddress: '127.0.0.1',
      remotePort: 41603,
      remoteFamily: 'IPv4',
      timeout: undefined,
      bytesWritten: 247,
      bytesRead: 120
    }
  }
}
```

**Comment by Skye-31** [comment]
This will be fixed by #1616 
Thanks for the report!
