### ISSUE TITLE
🐛 BUG: test failing sporadically in CI

### ISSUE THREAD

**Issue by cameron-robey** [cloudflare/wrangler2#1842]
### What version of `Wrangler` are you using?

2.1.*

### What operating system are you using?

Github Actions (multiple operating systems?)

### Describe the Bug

The following stack trace:

```
Error: R] [plugin wrangler-module-collector] The file ./other.other matched a module rule in your configuration ({"type":"Text","globs":["**/*.other"]}), but was ignored because a previous rule with the same type was not marked as `fallthrough = true`.

    ../../home/runner/work/wrangler2/wrangler2/packages/wrangler/src/module-collection.ts:244:14:
      244 │                 throw new Error(
          ╵                       ^

    at /home/runner/work/wrangler2/wrangler2/packages/wrangler/src/module-collection.ts:244:15
    at callback (/home/runner/work/wrangler2/wrangler2/node_modules/esbuild/lib/main.js:9[30](https://github.com/cloudflare/wrangler2/actions/runs/3047228304/jobs/4910983036#step:6:31):34)
    at handleRequest (/home/runner/work/wrangler2/wrangler2/node_modules/esbuild/lib/main.js:710:36)
    at handleIncomingPacket (/home/runner/work/wrangler2/wrangler2/node_modules/esbuild/lib/main.js:765:7)
    at Socket.readFromStdout (/home/runner/work/wrangler2/wrangler2/node_modules/esbuild/lib/main.js:641:7)
    at Socket.emit (node:events:390:28)
    at addChunk (node:internal/streams/readable:[31](https://github.com/cloudflare/wrangler2/actions/runs/3047228304/jobs/4910983036#step:6:32)5:12)
    at readableAddChunk (node:internal/streams/readable:289:9)
    at Socket.Readable.push (node:internal/streams/readable:228:10)
    at Pipe.onStreamRead (node:internal/stream_base_commons:199:23)

  This error came from the "onResolve" callback registered here:

    ../../home/runner/work/wrangler2/wrangler2/packages/wrangler/src/module-collection.ts:241:12:
      241 │             build.onResolve(
          ╵                   ~~~~~~~~~

    at onResolve (/home/runner/work/wrangler2/wrangler2/packages/wrangler/src/module-collection.ts:241:13)
    at Array.forEach (<anonymous>)
    at forEach (/home/runner/work/wrangler2/wrangler2/packages/wrangler/src/module-collection.ts:240:17)
    at Array.forEach (<anonymous>)
    at forEach (/home/runner/work/wrangler2/wrangler2/packages/wrangler/src/module-collection.ts:2[39](https://github.com/cloudflare/wrangler2/actions/runs/3047228304/jobs/4910983036#step:6:40):19)
    at handlePlugins (/home/runner/work/wrangler2/wrangler2/node_modules/esbuild/lib/main.js:852:23)
    at Object.buildOrServe (/home/runner/work/wrangler2/wrangler2/node_modules/esbuild/lib/main.js:11[46](https://github.com/cloudflare/wrangler2/actions/runs/3047228304/jobs/4910983036#step:6:47):7)
    at /home/runner/work/wrangler2/wrangler2/node_modules/esbuild/lib/main.js:2103:17
    at new Promise (<anonymous>)

  The plugin "wrangler-module-collector" was triggered by this import

    index.js:1:[50](https://github.com/cloudflare/wrangler2/actions/runs/3047228304/jobs/4910983036#step:6:51):
      1 │ ..../text.file'; import OTHER from './other.other'; export default {};
        ╵                                    ~~~~~~~~~~~~~~~
Error: R] [plugin wrangler-module-collector] The file ./other.other matched a module rule in your configuration ({"type":"Text","globs":["**/*.other"]}), but was ignored because a previous rule with the same type was not marked as `fallthrough = true`.

    ../../home/runner/work/wrangler2/wrangler2/packages/wrangler/src/module-collection.ts:244:14:
      244 │                 throw new Error(
          ╵                       ^

    at /home/runner/work/wrangler2/wrangler2/packages/wrangler/src/module-collection.ts:244:15
    at callback (/home/runner/work/wrangler2/wrangler2/node_modules/esbuild/lib/main.js:930:34)
    at handleRequest (/home/runner/work/wrangler2/wrangler2/node_modules/esbuild/lib/main.js:[71](https://github.com/cloudflare/wrangler2/actions/runs/3047228304/jobs/4911071101#step:6:72)0:36)
    at handleIncomingPacket (/home/runner/work/wrangler2/wrangler2/node_modules/esbuild/lib/main.js:[76](https://github.com/cloudflare/wrangler2/actions/runs/3047228304/jobs/4911071101#step:6:77)5:7)
    at Socket.readFromStdout (/home/runner/work/wrangler2/wrangler2/node_modules/esbuild/lib/main.js:641:7)
    at Socket.emit (node:events:390:28)
    at addChunk (node:internal/streams/readable:315:12)
    at readableAddChunk (node:internal/streams/readable:289:9)
    at Socket.Readable.push (node:internal/streams/readable:228:10)
    at Pipe.onStreamRead (node:internal/stream_base_commons:199:23)

  This error came from the "onResolve" callback registered here:

    ../../home/runner/work/wrangler2/wrangler2/packages/wrangler/src/module-collection.ts:241:12:
      241 │             build.onResolve(
          ╵                   ~~~~~~~~~

    at onResolve (/home/runner/work/wrangler2/wrangler2/packages/wrangler/src/module-collection.ts:241:13)
    at Array.forEach (<anonymous>)
    at forEach (/home/runner/work/wrangler2/wrangler2/packages/wrangler/src/module-collection.ts:240:17)
    at Array.forEach (<anonymous>)
    at forEach (/home/runner/work/wrangler2/wrangler2/packages/wrangler/src/module-collection.ts:239:19)
    at handlePlugins (/home/runner/work/wrangler2/wrangler2/node_modules/esbuild/lib/main.js:[85](https://github.com/cloudflare/wrangler2/actions/runs/3047228304/jobs/4911071101#step:6:86)2:23)
    at Object.buildOrServe (/home/runner/work/wrangler2/wrangler2/node_modules/esbuild/lib/main.js:1146:7)
    at /home/runner/work/wrangler2/wrangler2/node_modules/esbuild/lib/main.js:2103:17
    at new Promise (<anonymous>)

  The plugin "wrangler-module-collector" was triggered by this import

    index.js:1:50:
      1 │ ..../text.file'; import OTHER from './other.other'; export default {};
        ╵                                    ~~~~~~~~~~~~~~~

Error: R] [plugin checkForNodeBuiltins] Detected a Node builtin module import while Node compatibility is disabled.
Add node_compat = true to your wrangler.toml file to enable Node compatibility.

    index.js:2:23:
      2 │       import path from 'path';
        ╵                        ~~~~~~

  This error came from the "onResolve" callback registered here:

    ../../home/runner/work/wrangler2/wrangler2/packages/wrangler/src/bundle.ts:38:8:
      38 │     build.onResolve(
         ╵           ~~~~~~~~~

    at onResolve (/home/runner/work/wrangler2/wrangler2/packages/wrangler/src/bundle.ts:38:9)
    at handlePlugins (/home/runner/work/wrangler2/wrangler2/node_modules/esbuild/lib/main.js:852:23)
    at Object.buildOrServe (/home/runner/work/wrangler2/wrangler2/node_modules/esbuild/lib/main.js:1146:7)
    at /home/runner/work/wrangler2/wrangler2/node_modules/esbuild/lib/main.js:2103:17
    at new Promise (<anonymous>)
    at Object.build (/home/runner/work/wrangler2/wrangler2/node_modules/esbuild/lib/main.js:2102:14)
    at Object.build (/home/runner/work/wrangler2/wrangler2/node_modules/esbuild/lib/main.js:1[94](https://github.com/cloudflare/wrangler2/actions/runs/3047228304/jobs/4911071101#step:6:95)9:51)
    at build (/home/runner/work/wrangler2/wrangler2/packages/wrangler/src/bundle.ts:227:31)
    at publish (/home/runner/work/wrangler2/wrangler2/packages/wrangler/src/publish.ts:402:6)
```

**Comment by cameron-robey** [comment]
Actually was tests failing below just being masked by this...
