### ISSUE TITLE
🐛 BUG: Uncaught TypeError: globalThis.XMLHttpRequest is not a constructor

### ISSUE THREAD

**Issue by 0xYYY** [cloudflare/wrangler2#1963]
### What version of `Wrangler` are you using?

2.1.9

### What operating system are you using?

Mac

### Describe the Bug

Minimal repo to reproduce the bug: https://github.com/0xYYY/alpaca-excerpt-bot

Running `wrangler publish` will result in the following error:
```
 ⛅️ wrangler 2.1.9
-------------------
▲ [WARNING] Enabling node.js compatibility mode for built-ins and globals. This is experimental and has serious tradeoffs. Please see https://github.com/ionic-team/rollup-plugin-node-polyfills/ for more details.


Total Upload: 2207.36 KiB / gzip: 399.23 KiB

✘ [ERROR] A request to the Cloudflare API (/accounts/314050a9a9d7e9c63b202201e738c2ac/workers/scripts/alpaca-excerpt-bot) failed.

  Uncaught TypeError: globalThis.XMLHttpRequest is not a constructor
    at index.js:4548:11 in checkTypeSupport
    at index.js:4569:38 in
  node_modules/rollup-plugin-node-polyfills/polyfills/http-lib/capability.js
    at index.js:15:56 in __init
    at index.js:9073:5 in
  node_modules/rollup-plugin-node-polyfills/polyfills/http-lib/request.js
    at index.js:15:56 in __init
    at index.js:10166:5 in node-modules-polyfills:https
    at index.js:15:56 in __init
    at index.js:10270:21 in node-modules-polyfills-commonjs:https
    at index.js:18:50 in __require2
    at index.js:12865:17 in
  node_modules/node-telegram-bot-api/src/telegramWebHook.js
   [code: 10021]


  If you think this is a bug, please open an issue at:
  https://github.com/cloudflare/wrangler2/issues/new/choose
```

**Comment by KianNH** [comment]
Looks like you're relying on a Node package - the `node_compat` polyfills won't fix every Node API that a package might rely on.

In particular, Workers don't have `XMLHttpRequest`, they have the `fetch` web API. You'll have to polyfill that or find a package that is suited for browsers/Workers.

**Comment by 0xYYY** [comment]
Understood, thanks for the explanation. I'll close this issue then.
