### ISSUE TITLE
🚀 Feature Request: Add support for custom local hostnames

### ISSUE THREAD

**Issue by Hexstream** [cloudflare/wrangler2#1994]
### Describe the solution

Hello,

I am managing 25+ subdomains.

Right now, if I start multiple instances of `wrangler pages dev` (on multiple ports), I get URLs like:

```
https://127.0.0.1:8788/
https://127.0.0.1:8789/
https://127.0.0.1:8790/
```

I would much rather use URLs like:
```
https://dev.www.hexstreamsoft.com:8788/
https://dev.clos-mop.hexstreamsoft.com:8789/
https://dev.notes-and-tips.hexstreamsoft.com:8790/
```

So for instance, I added a mapping from `dev.www.hexstreamsoft.com` to `127.0.0.1` in my `/etc/hosts/` file.

However, after starting `wrangler pages dev public --local-protocol https` and successfully opening `https://127.0.0.1:8788/`, `https://dev.www.hexstreamsoft.com:8788/` does not work:

![custom-local-hostname-https.png](https://www.hexstreamsoft.com/tmp/custom-local-hostname-https.png)

After starting `wrangler pages dev public` and successfully opening `http://127.0.0.1:8788/`, `http://dev.www.hexstreamsoft.com:8788/` does not work. First of all, this redirects to `https://dev.www.hexstreamsoft.com:8788/` because of the HSTS, and then I get this:

![custom-local-hostname-http.png](https://www.hexstreamsoft.com/tmp/custom-local-hostname-http.png)

**Comment by caass** [comment]
Thanks for bringing this up! We've added it to our issue backlog :)

**Comment by Hexstream** [comment]
Thank you!! This will be a tremendous boon for usability!!

**Comment by Wallacy** [comment]
FWIW:

I do that on miniflare 2 + worker sites; I have one of my domains with a DNS pointing to 127.0.0.1, and a wildcard DNS point to the root. My worker will receive all requests and handle appropriate for each subdomain. I cant do the same on wrangler2, then i still need to use miniflare for that.

Thats is also why i still use worker sites, because i can do much more.

Will be nice to be able to setup a base hostname, and still accept any subdomain request like we do on miniflare today.

**Comment by CarmenPopoviciu** [comment]
hi folks,

looking at the original report, I'm seeing the page is blocked on `NET::ERR_CERT_AUTHORITY_INVALID`, so I'm wondering if the issues y'all are experiencing are not security certificates related. Back when this issue was raised, wrangler only supported self-signed certificates. That changed however with the landing of https://github.com/cloudflare/workers-sdk/pull/4475. You can now pass the 
`--https-key-path` and `--https-cert-path` to your `pages dev` command to use your own ssl certificates. 

Would be good to confirm whether that fixes the issue for you

**Comment by Hexstream** [comment]
Thank you, I want to try this solution, unfortunately I am not yet familiar with manually generating local development certificates, so I have some reading to do. Ideally, I would want just one certificate for all my local `dev.*` domain names that I would declare in my `hosts` file.

I have started looking at [mkcert](https://github.com/FiloSottile/mkcert), and am open to other suggestions.

(Maybe wrangler could provide an easy way to generate such local development certificates?)

**Comment by CarmenPopoviciu** [comment]
I am not very familiar with generating ssl certificates for local dev either, but `mkcert` seems like a good place to start (also see https://web.dev/articles/how-to-use-local-https).

I need to inquire on whether we have an official recommendation for such a tool, but if we do, we can definitely add that to our docs (great idea!). I'll circle back here once I know more

**Comment by CarmenPopoviciu** [comment]
I can confirm that `mkcert` is indeed a good option. I'll look into whether I can open a PR to our docs. In the meanwhile, please keep us posted if using the custom certificate solved your issue <3

**Comment by Hexstream** [comment]
Great! I'm on it!

**Comment by petebacondarwin** [comment]
@Hexstream - could I ask if there is a specific reason why you want to turn on `--local-protocol=https` in your local development?

**Comment by Hexstream** [comment]
@CarmenPopoviciu **_Great news!_ [mkcert](https://github.com/FiloSottile/mkcert) is 100% painless, and I quickly got the results I want in every way, _except for one critical usability issue:_**

Pressing `b` in wrangler opens for instance
`https://localhost:8800/` instead of
`https://dev.abc.hexstream.xyz:8800/`.

**So I just need a way to pass `--hostname dev.abc.hexstream.xyz` or similar to wrangler.**

-----

So here is what I did, it's quite trivial.

- I added the 32 dev domain names as an alias for `127.0.0.1` to my `/etc/hosts` file.

- For [installing mkcert](https://github.com/FiloSottile/mkcert?tab=readme-ov-file#linux), `libnss3-tools` was already installed, so I just installed the pre-built binaries.

- I invoked `mkcert -install` to install the CA.

- I generated my certificate for my 32 dev domains with `mkcert [32 domains like dev.abc.hexstream.xyz]` while in `/home/hexstream/apps/mkcert/`, then renamed the files to `key.pem` and `cert.pem`. (I could have used the `-key-file` and `-cert-file` options instead.)

- I edited my usual wrangler invocations to look like this:
 `wrangler pages dev public --local-protocol https --port 8800 --https-key-path /home/hexstream/apps/mkcert/key.pem --https-cert-path /home/hexstream/apps/mkcert/cert.pem`

- I started `wrangler pages dev` per above, then pressed `b` and then edited the URL to be `https://dev.abc.hexstream.xyz:8800/` instead of `https://localhost:8800/`.

_That's all!_ Now we just need to eliminate the "edit the URL" part and we're golden!

-----

@petebacondarwin Yes, [there are various limitations in using `http:localhost` as a secure context](https://web.dev/articles/when-to-use-local-https), which I just don't want to deal with. I'm sure you appreciate the convenience of the development environment being nearly identical to production wherever possible...

Anyway I really want to use nice dev hostnames like `dev.abc.hexstream.xyz`, and I use HSTS everywhere, so HTTPS is inherently required. HTTP is just not accessible.

We're already almost there anyway, I just need the `--hostname` feature requested above and we're done!

**Comment by CarmenPopoviciu** [comment]
I think what we need here is for `pages dev` to support the `--ip` flag just like `wrangler dev` (see https://developers.cloudflare.com/workers/wrangler/commands/#dev). This should be fairly straightforward to add

**Comment by CarmenPopoviciu** [comment]
oh, actually ignore that last bit in my comment. `pages dev` already supports the `--ip` flag. @Hexstream can you please give that a try and let me know if that solved your issue?

**Comment by Hexstream** [comment]
Unfortunately, `--ip dev.abc.hexstream.xyz` does not work, I thought it would since in the console it says `[wrangler:inf] Ready on https://dev.abc.hexstream.xyz:8800`, but pressing `b` mysteriously opens `https://127.0.0.1:36323/`, which doesn't work.

Manually fixing this to `https://dev.abc.hexstream.xyz:8800/` works.

(Also `--ip` sounds like a bit of a misnomer in this case, I think `--hostname` would be a bit better...)

**Comment by petebacondarwin** [comment]
> (Also, --ip sounds like a bit of a misnomer in this case, I think --hostname (or --host?) would be a bit better...)

As an aside here, the various ip, host, hostname, upstream, etc names here are really confusing, since there are a number of concepts that need to be managed. In Workers generally, the hostname type terminology is the host where the Worker being debugged "believes" it is being hosted. In other words, this is the host on the `request` object passed to the Worker. This is significant when Workers are being used as middleware/proxies in front of an origin server, since calling fetch with the Worker's hostname will make a request to the origin not to the Worker.

**Comment by Hexstream** [comment]
@CarmenPopoviciu Here is the log for `wrangler pages dev public --local-protocol https --ip dev.abc.hexstream.xyz --https-key-path /home/hexstream/apps/mkcert/key.pem --https-cert-path /home/hexstream/apps/mkcert/cert.pem --log-level debug`, unfortunately it's not quite as useful as I anticipated, it doesn't even mention `dev.abc.hexstream.xyz` (nor the command line), and `--log-level debug` does almost nothing more compared to omitting that argument...

```

--- 2024-07-01T15:01:04.004Z debug
🪵  Writing logs to "/home/hexstream/.wrangler/logs/wrangler-2024-07-01_15-01-03_866.log"
---

--- 2024-07-01T15:01:04.004Z debug
Failed to load .env file ".env": Error: ENOENT: no such file or directory, open '.env'
    at Object.openSync (node:fs:582:18)
    at Object.readFileSync (node:fs:461:35)
    at tryLoadDotEnv (/home/hexstream/.volta/tools/image/packages/wrangler/lib/node_modules/wrangler/wrangler-dist/cli.js:158768:72)
    at loadDotEnv (/home/hexstream/.volta/tools/image/packages/wrangler/lib/node_modules/wrangler/wrangler-dist/cli.js:158777:12)
    at /home/hexstream/.volta/tools/image/packages/wrangler/lib/node_modules/wrangler/wrangler-dist/cli.js:202740:20
    at /home/hexstream/.volta/tools/image/packages/wrangler/lib/node_modules/wrangler/wrangler-dist/cli.js:162911:16
    at maybeAsyncResult (/home/hexstream/.volta/tools/image/packages/wrangler/lib/node_modules/wrangler/wrangler-dist/cli.js:161132:44)
    at /home/hexstream/.volta/tools/image/packages/wrangler/lib/node_modules/wrangler/wrangler-dist/cli.js:162910:14
    at /home/hexstream/.volta/tools/image/packages/wrangler/lib/node_modules/wrangler/wrangler-dist/cli.js:161119:22
    at Array.reduce (<anonymous>) {
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: '.env'
}
---

--- 2024-07-01T15:01:04.016Z log

 ⛅️ wrangler 3.62.0
[38;2;255;136;0m-------------------[39m

---

--- 2024-07-01T15:01:04.057Z warn
[33m▲ [43;33m[[43;30mWARNING[43;33m][0m [1mNo compatibility_date was specified. Using today's date: 2024-07-01.[0m

  ❯❯ Add one to your wrangler.toml file: compatibility_date = "2024-07-01", or
  ❯❯ Pass it in your terminal: wrangler pages dev [<DIRECTORY>] --compatibility-date=2024-07-01
  
  See [4mhttps://developers.cloudflare.com/workers/platform/compatibility-dates/[0m for more information.


---

--- 2024-07-01T15:01:04.058Z log
No functions. Shimming...
---

--- 2024-07-01T15:01:04.072Z debug
Retrieving cached values for userId from node_modules/.cache/wrangler
---

--- 2024-07-01T15:01:04.072Z debug
Metrics dispatcher: Posting data {"type":"event","name":"run dev","properties":{"local":true,"usesTypeScript":true}}
---

--- 2024-07-01T15:01:04.080Z debug
Failed to load .env file "/home/hexstream/data/projects/websites/hexstream.xyz/abc.hexstream.xyz/.dev.vars": Error: ENOENT: no such file or directory, open '/home/hexstream/data/projects/websites/hexstream.xyz/abc.hexstream.xyz/.dev.vars'
    at Object.openSync (node:fs:582:18)
    at Object.readFileSync (node:fs:461:35)
    at tryLoadDotEnv (/home/hexstream/.volta/tools/image/packages/wrangler/lib/node_modules/wrangler/wrangler-dist/cli.js:158768:72)
    at loadDotEnv (/home/hexstream/.volta/tools/image/packages/wrangler/lib/node_modules/wrangler/wrangler-dist/cli.js:158777:12)
    at getVarsForDev (/home/hexstream/.volta/tools/image/packages/wrangler/lib/node_modules/wrangler/wrangler-dist/cli.js:200152:18)
    at getBindings (/home/hexstream/.volta/tools/image/packages/wrangler/lib/node_modules/wrangler/wrangler-dist/cli.js:207740:10)
    at getBindingsAndAssetPaths (/home/hexstream/.volta/tools/image/packages/wrangler/lib/node_modules/wrangler/wrangler-dist/cli.js:207621:20)
    at getDevReactElement (/home/hexstream/.volta/tools/image/packages/wrangler/lib/node_modules/wrangler/wrangler-dist/cli.js:207276:40)
    at startDev (/home/hexstream/.volta/tools/image/packages/wrangler/lib/node_modules/wrangler/wrangler-dist/cli.js:207343:60)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: '/home/hexstream/data/projects/websites/hexstream.xyz/abc.hexstream.xyz/.dev.vars'
}
---

--- 2024-07-01T15:01:04.139Z log
Using custom certificate at  /home/hexstream/apps/mkcert/key.pem
---

--- 2024-07-01T15:01:04.205Z log
[2m⎔ Starting local server...[22m
---

--- 2024-07-01T15:01:04.392Z log
✨ Parsed 2 valid header rules.
---

--- 2024-07-01T15:01:04.417Z debug
[InspectorProxyWorker] handleProxyControllerIncomingMessage {"type":"reloadStart"}
---

--- 2024-07-01T15:01:04.538Z error
[31m✘ [41;31m[[41;97mERROR[41;31m][0m [1mworkerd/server/server.c++:3448: info: Inspector is listening[0m


---

--- 2024-07-01T15:01:04.542Z debug
Metrics dispatcher: Posting data {"type":"event","name":"run pages dev","properties":{}}
---

--- 2024-07-01T15:01:04.551Z debug
[InspectorProxyWorker] handleProxyControllerIncomingMessage {"type":"reloadComplete","proxyData":{"userWorkerUrl":{"protocol":"http:","hostname":"127.0.0.1","port":"35673"},"userWorkerInspectorUrl":{"protocol":"ws:","hostname":"127.0.0.1","port":"39739","pathname":"/core:user:worker"},"userWorkerInnerUrlOverrides":{"protocol":"https"},"headers":{"MF-Proxy-Shared-Secret":"1191d008-224e-4d8f-b909-c6ebabe39be1"},"liveReload":false,"proxyLogsToController":false,"internalDurableObjects":[],"entrypointAddresses":{"__INTERNAL_WRANGLER_MIDDLEWARE__":{"host":"127.0.0.1","port":44795},"default":{"host":"127.0.0.1","port":45355}}}}
---

--- 2024-07-01T15:01:04.554Z debug
[InspectorProxyWorker] reconnectRuntimeWebSocket
---

--- 2024-07-01T15:01:04.557Z error
[31m✘ [41;31m[[41;97mERROR[41;31m][0m [1mworkerd/server/server.c++:1220: info: Inspector client attaching [core:user:worker][0m


---

--- 2024-07-01T15:01:04.561Z debug
[InspectorProxyWorker] NEW RUNTIME WEBSOCKET http://127.0.0.1:39739/core:user:worker
---

--- 2024-07-01T15:01:04.564Z debug
[InspectorProxyWorker] RUNTIME INCOMING MESSAGE {
  method: 'Runtime.executionContextCreated',
  params: {
    context: {
      id: 355797089,
      origin: '',
      name: 'Worker',
      uniqueId: '-8642599922537279942.-7841921188685164253'
    }
  }
}
---

--- 2024-07-01T15:01:04.567Z debug
[InspectorProxyWorker] RUNTIME INCOMING MESSAGE { id: 100000001, result: {} }
---

--- 2024-07-01T15:01:04.569Z debug
[InspectorProxyWorker] SEND TO DEVTOOLS {"method":"Runtime.executionContextsCleared"}
---

--- 2024-07-01T15:01:04.572Z debug
[InspectorProxyWorker] RUNTIME WEBSOCKET OPENED
---

--- 2024-07-01T15:01:04.575Z debug
[InspectorProxyWorker] SEND TO RUNTIME {"method":"Runtime.enable","id":100000001}
---

--- 2024-07-01T15:01:04.578Z debug
[InspectorProxyWorker] SEND TO RUNTIME {"method":"Debugger.enable","id":100000002}
---

--- 2024-07-01T15:01:04.581Z debug
[InspectorProxyWorker] SEND TO RUNTIME {"method":"Network.enable","id":100000003}
---

--- 2024-07-01T15:01:04.584Z debug
[InspectorProxyWorker] RUNTIME INCOMING MESSAGE {
  method: 'Debugger.scriptParsed',
  params: {
    scriptId: '3',
    url: 'file:///home/hexstream/data/projects/websites/hexstream.xyz/abc.hexstream.xyz/.wrangler/tmp/dev-dBNgnA/pages-shim.js',
    startLine: 0,
    startColumn: 0,
    endLine: 199,
    endColumn: 130,
    executionContextId: 355797089,
    hash: '92fae1739b2628f1a1b651d529400fa86ff59080aa6409fdae0f90ebe0906111',
    isLiveEdit: false,
    sourceMapURL: 'pages-shim.js.map',
    hasSourceURL: true,
    isModule: true,
    length: 6573,
    scriptLanguage: 'JavaScript',
    embedderName: 'pages-shim.js'
  }
}
---

--- 2024-07-01T15:01:04.585Z debug
[InspectorProxyWorker] RUNTIME INCOMING MESSAGE {
  id: 100000002,
  result: { debuggerId: '6854278076421548368.-8686340897058967431' }
}
---

--- 2024-07-01T15:01:04.587Z debug
[InspectorProxyWorker] RUNTIME INCOMING MESSAGE { id: 100000003, method: 'Network.enable', result: {} }
---

--- 2024-07-01T15:01:14.552Z debug
[InspectorProxyWorker] SEND TO RUNTIME {"method":"Runtime.getIsolateId","id":100000004}
---

--- 2024-07-01T15:01:14.557Z debug
[InspectorProxyWorker] RUNTIME INCOMING MESSAGE { id: 100000004, result: { id: '56b98f376911ea16' } }
---
```

**Comment by Hexstream** [comment]
(Added my terminal in an edit above, for completeness.)

**Comment by Hexstream** [comment]
(Edited twice above to include more details...)

**Comment by Hexstream** [comment]
One thing I notice is that if pressing `b` opens a wrong url like `https://127.0.0.1:43111/`, then editing it to `http://127.0.0.1:43111/` (removing the `s`) does work, which is baffling since I specified `--local-protocol https --port 8800`. 

(I had sometimes forgotten the `--port` option above, but it substantially doesn't change anything.)

**Comment by CarmenPopoviciu** [comment]
I'll need to debug this a bit and understand why this is happening. `pages dev` definitely takes in those args correctly, so I *think* the problem is somewhere further down the line

**Comment by CarmenPopoviciu** [comment]
just out of curiosity...how does smth like `wrangler pages dev [directory] --ip dev.Hexstream.abc --local-protocol https` behave like for you if you press `b`?

**Comment by CarmenPopoviciu** [comment]
nope, that's what I was looking for. thank you 🙏
