### ISSUE TITLE
🐛 BUG: cannot create table locally

### ISSUE THREAD

**Issue by kingmesal** [cloudflare/wrangler2#2009]
### What version of `Wrangler` are you using?

0.0.0-200c7f22

### What operating system are you using?

Linux

### Describe the Bug

Trying to create a new table in a newly created database...
CUSTOMER_DB is the name of the d1 database binding in my wrangler.toml 

Loading DB at .wrangler/state/d1/CUSTOMER_DB.sqlite3

✘ [ERROR] require is not defined

When I run the same script remotely (without the --local flag) against D1 all is well.

**Comment by kingmesal** [comment]
When trying to run wrangler on my pages project with --local as well...

```Starting inspector on 0.0.0.0:9229 failed: address already in use
ReferenceError: require is not defined
    at _resolve (file:///home/me/Projects/api/node_modules/npx-import/lib/utils.js:11:5)
    at npxResolve (file:///home/me/Projects/api/node_modules/npx-import/lib/index.js:56:16)
    at createSQLiteDB (/home/me/Projects/api/node_modules/@miniflare/shared/src/sqlite.ts:20:51)
    at FileStorage.getSqliteDatabase (/home/me/Projects/api/node_modules/@miniflare/storage-file/src/index.ts:114:21)
    at D1Plugin.getBetaDatabase (/home/me/Projects/api/node_modules/miniflare/node_modules/@miniflare/d1/src/plugin.ts:50:29)
    at D1Plugin.setup (/home/me/Projects/api/node_modules/miniflare/node_modules/@miniflare/d1/src/plugin.ts:57:28)
    at EventTarget.#runSetup (/home/me/Projects/api/node_modules/@miniflare/core/src/index.ts:327:20)
✘ [ERROR] Miniflare process exited with code 1```

**Comment by kingmesal** [comment]
Forced rollback to version
        "wrangler": "^0.0.0-7c228171"
made it so my stuff works again.

**Comment by caass** [comment]
Ah ok, thanks for reporting! This looks like an issue where we're using [npx-import](https://github.com/geelen/npx-import) but for some reason the context we're running it in doesn't have access to `require`, i.e. not in a NodeJS context.

**Comment by rozenmd** [comment]
This was resolved by https://github.com/geelen/npx-import/pull/9, updating wrangler should resolve the issue (let us know if not!)
