### ISSUE TITLE
🐛 BUG: D1 on local DB not working

### ISSUE THREAD

**Issue by netnose** [cloudflare/wrangler2#2133]
### What version of `Wrangler` are you using?

0.0.0-b918fc06

### What operating system are you using?

Mac M1

### Describe the Bug

I'm following the D1 Getting Started at https://developers.cloudflare.com/d1/get-started/.
When I run commands on remote DB, all commands are processed correctly.
When I run on local DB, I get some errors:

- `npx wrangler d1 execute <database-name> --file=./schema.sql --local` throws an error `✘ [ERROR] no such column: Bs Beverages`;
- after running the schema.sql file with sqlite3, the command `npx wrangler d1 execute test-db --command='SELECT * FROM Customers' --local` returns the correct data;
- when running `npx wrangler dev --local`, the error "no such table: Customers" is returned, here is the stack trace:

> GET /api/beverages: SqliteError: no such table: Customers
    at Database.prepare (/Users/mirko/.npm/_npx/485d09d313c7e301/node_modules/better-sqlite3/lib/methods/wrappers.js:5:21)
    at Statement.#prepareAndBind (/Users/mirko/Development/cf-d1-test/node_modules/@miniflare/d1/src/statement.ts:39:31)
    at Statement.all (/Users/mirko/Development/cf-d1-test/node_modules/@miniflare/d1/src/statement.ts:58:35)
    at Object.fetch (/Users/mirko/Development/cf-d1-test/src/index.ts:31:6)
    at Object.fetch (/private/Users/mirko/Development/cf-d1-test/node_modules/wrangler/templates/d1-beta-facade.js:168:17)
    at /Users/mirko/Development/cf-d1-test/node_modules/@miniflare/core/src/standards/event.ts:350:19
    at /Users/mirko/Development/cf-d1-test/node_modules/@miniflare/shared/src/event.ts:29:9
    at EventTarget.<anonymous> (/Users/mirko/Development/cf-d1-test/node_modules/@miniflare/shared/src/event.ts:77:9)
    at EventTarget.[nodejs.internal.kHybridDispatch] (node:internal/event_target:643:20)
    at EventTarget.dispatchEvent (node:internal/event_target:585:26)

- after `npx wrangler publish` the online version works well.

**Comment by rozenmd** [comment]
Hey @netnose - I've made a PR fixing the docs, currently waiting for it to get merged. 

You can resolve it locally by replacing `"` with `'` in the schema.sql

**Comment by netnose** [comment]
Hi @rozenmd,
cool, thanks.
I confirm that replacing quotes works for the execute command.

The local dev is still not working.

**Comment by rozenmd** [comment]
Figured this one out @netnose, you need to run `npx wrangler dev --local --persist` to actually see local data in d1. 

I'll update the docs.

**Comment by netnose** [comment]
Thank you!
