### ISSUE TITLE
🐛 BUG: `wrangler dev` fails to start due to `getaddrinfo ENOTFOUND`

### ISSUE THREAD

**Issue by demosjarco** [cloudflare/wrangler2#2149]
### What version of `Wrangler` are you using?

2.1.15

### What operating system are you using?

Windows 11 21H1

### Describe the Bug

When a workers script is deployed to a custom domain, and that domain is a subdomain of the zone, and the zone does not have any content, `wrangler dev` fails to launch.

Example: `api.example.com` (the worker) works just fine and `example.com` is intentionally empty (no `A`/`CNAME` records)

Error log:
```
✘ [ERROR] Error while creating remote dev session: TypeError: fetch failed

      at fetch8 (<REDACTED>\node_modules\wrangler\wrangler-dist\cli.js:13702:17)
      at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
      at async createPreviewSession
  (<REDACTED>\node_modules\wrangler\wrangler-dist\cli.js:144445:28)
      at async start (<REDACTED>\node_modules\wrangler\wrangler-dist\cli.js:145088:9)
  {
    cause: Error: getaddrinfo ENOTFOUND <REDACTED>
        at GetAddrInfoReqWrap.onlookup [as oncomplete] (node:dns:107:26) {
      errno: -3008,
      code: 'ENOTFOUND',
      syscall: 'getaddrinfo',
      hostname: '<REDACTED>'
    }
  }
```

Running `wrangler dev` fails
Running `wrangler dev --local` works just fine
Running `wrangler publish` and then visiting the subdomain works just fine

**Comment by demosjarco** [comment]
To me this seems like some sort of uptime check where it does a DNS query for the root domain, instead of the exact domain listed in `route` in the `wrangler.toml`.

**Comment by JacobMGEvans** [comment]
Interesting, thank you for taking the time to report this.

**Comment by JacobMGEvans** [comment]
Just a follow up, we are looking into this currently. Sorry for the delay

**Comment by jspspike** [comment]
Could you please show your `wrangler.toml` to see what your routes are set to? And run wrangler with log level set to debug?
