### ISSUE TITLE
🐛 BUG: D1 databases can be created but they do not persist after the worker has stopped

### ISSUE THREAD

**Issue by Benjamin-del** [cloudflare/wrangler2#2285]
### What version of `Wrangler` are you using?

2.4.4

### What operating system are you using?

Windows 11

### Describe the Bug

Wrangler D1 databases can be created but they do not persist after the worker has stoped...

Creating table and executing with execute command (Returns table):

```
DROP TABLE IF EXISTS Customers;
CREATE TABLE Customers (CustomerID INT, CompanyName TEXT, ContactName TEXT, PRIMARY KEY (`CustomerID`));
INSERT INTO Customers (CustomerID, CompanyName, ContactName) VALUES (1, 'Alfreds Futterkiste', 'Maria Anders'), (4, 'Around the Horn', 'Thomas Hardy'), (11, 'Bs Beverages', 'Victoria Ashworth'), (13, 'Bs Beverages', 'Random Name');
SELECT * FROM Customers;
```

In the worker reading the table:

`const { results } = await env.DB.prepare("SELECT * FROM Customers WHERE CompanyName = ?").bind("Bs Beverages").all();`

Returns this error:

```
SqliteError: no such table: Customers
    at Database.prepare (C:\Users\me\d1-test\node_modules\better-sqlite3\lib\methods\wrappers.js:5:21)
    at Statement.#prepareAndBind (C:\Users\me\d1-test\node_modules\@miniflare\d1\src\statement.ts:39:31)
    at Statement.all (C:\Users\me\d1-test\node_modules\@miniflare\d1\src\statement.ts:58:35)
    at D1QB2.<anonymous> (C:\Users\me\AppData\d1-test\node_modules\workers-qb\dist\esm\Databases.js:73:48)
    at step (C:\Users\me\AppData\d1-test\node_modules\workers-qb\dist\esm\Databases.js:47:23)
    at Object.next (C:\Users\me\AppData\d1-test\node_modules\workers-qb\dist\esm\Databases.js:28:53)
    at C:\Users\me\AppData\d1-test\node_modules\workers-qb\dist\esm\Databases.js:22:71
    at new Promise (<anonymous>)
    at __awaiter (C:\Users\me\AppData\d1-test\node_modules\workers-qb\dist\esm\Databases.js:18:12)
    at D1QB2.execute (C:\Users\me\AppData\d1-test\node_modules\workers-qb\dist\esm\Databases.js:62:16)
```

**Comment by rozenmd** [comment]
Hey @Benjamin-del what was the wrangler command you used?

Note that to persist a `--local` command, you'll need to add `--persist`

**Comment by Benjamin-del** [comment]
I was probably missing the  --persist command. I will look into it.
