### ISSUE TITLE
🐛 BUG:

### ISSUE THREAD

**Issue by mrbm** [cloudflare/wrangler2#2433]
### What version of `Wrangler` are you using?

2.5.2 - 2.6.2

### What operating system are you using?

Mac m1 Ventura

### Describe the Bug

Have a previously working project started with wrangler 2

I can still publish without issue, but when attempting to tail getting a stange error now. First it will attempt to login via oauth, ie:

```
% wrangler tail pretty 
 ⛅️ wrangler 2.6.2 
-------------------
Attempting to login via OAuth...
Opening a link in your default browser: 
https://dash.cloudflare.com/oauth2/auth?response_type=code&client_id=XXXXXXXX-XXXX-XXXX-eXXXX&redirect_uri=http%3A%2F%2Flocalhost%3A8976%2Foauth%2Fcallback&scope=account%3Aread%20user%3Aread%20workers%3Awrite%20workers_kv%3Awrite%20workers_routes%3Awrite%20workers_scripts%3Awrite%20workers_tail%3Aread%20d1%3Awrite%20pages%3Awrite%20zone%3Aread%20offline_access&state=XXXXXX-XXXX.DXXXXXXXXXXX4&code_challenge=fJL1vXXXXXXXXXXXXXXy_yhXXXXXXXXXc&code_challenge_method=S256

```
Then I go browser authenticate, and then it redirects to a local host path and fails. Not sure why its pointing to a local host path.

I then try via sudo:
```
% sudo wrangler tail pretty
▲ [WARNING] It looks like you have used Wrangler 1's `config` command to login with an API token.

  This is no longer supported in the current version of Wrangler.
  If you wish to authenticate via an API token then please set the `CLOUDFLARE_API_TOKEN`
  environment variable.


 ⛅️ wrangler 2.6.2 
-------------------

✘ [ERROR] A request to the Cloudflare API (/accounts/05XXXXXXXXXXXXXXXX/workers/scripts/pretty/bindings) failed.

  workers.api.error.script_not_found [code: 10007]
  
  If you think this is a bug, please open an issue at:
  https://github.com/cloudflare/wrangler2/issues/new/choose

```
Very strange to me because I have no issues publishing

Thanks

**Comment by JacobMGEvans** [comment]
Added a title, appreciate you adding the issue from the Discord chat we had 👍🏻

**Comment by ninsiu-com** [comment]
Same Error in wrangler 3.1.0,  Doesn't know why redirect to Localhost ? Is wrangler listen at http://localhost:8976/oauth/callback ?

**Comment by penalosa** [comment]
@ninsiu-com Could you provide more details about what's going wrong? Wrangler should be listening at that path for an OAuth callback.

What happens when you run `npx wrangler login`?

**Comment by ninsiu-com** [comment]
> @ninsiu-com Could you provide more details about what's going wrong? Wrangler should be listening at that path for an OAuth callback.
> 
> What happens when you run `npx wrangler login`?

Thanks, I've checked again. It's the network communication error in the `exchangeAuthCodeForAccessToken()` process. Not Local Problem.

**Comment by digitpain** [comment]
I am also having this issue and cannot login with `wrangler login` on `3.1.1`.

**Comment by jspspike** [comment]
We haven't heard back on this issue in a while, so I'm going to close this  for now. If you're still running into issues feel free to comment with more details and we can re-open and investigate further! Thanks!

**Comment by mattcox** [comment]
I'm still seeing this. M1 Mac with MacOS Sonoma installed. If I try the login, (attempted with both Safari and Chrome) redirect to Cloudflare, I go through the login process, and then the website fails to load redirecting to some localhost address.

This error pops up in the console:
```
 ⛅️ wrangler 3.11.0
-------------------
Attempting to login via OAuth...
Opening a link in your default browser: https://dash.cloudflare.com/oauth2/auth?response_type=code&client_id=...
/Users/matt/Development/RemixCD/remixcontent/node_modules/wrangler/wrangler-dist/cli.js:29374
            throw a;
            ^

Error: EACCES: permission denied, mkdir '/Users/matt/.wrangler/config'
    at mkdirSync (node:fs:1382:3)
    at writeAuthConfigFile (/Users/matt/Development/RemixCD/remixcontent/node_modules/wrangler/wrangler-dist/cli.js:120783:33)
    at Server.<anonymous> (/Users/matt/Development/RemixCD/remixcontent/node_modules/wrangler/wrangler-dist/cli.js:120875:13)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  errno: -13,
  syscall: 'mkdir',
  code: 'EACCES',
  path: '/Users/matt/.wrangler/config'
}

Node.js v19.6.0
```

Unsure how to proceed.

**Comment by christidis** [comment]
I am having the same issue when I was trying to create a worker in Cloudflare as both `login` and `deploy` subcommands redirect at some point to `localhost:8976`.

**Comment by mrbm** [comment]
@christidis something that really helped me was deleting and re-installing apple x-code command line tools. My set up has been migrated from computer to computer over the years via time machine, perhaps that messes something up. deleting (very important as I had it already installed) and then re-installing the x-code command line tools seems to fix some oddities that I had been having. TRY IT!

**Comment by felix-hh** [comment]
Had the same issue. Port forwarding as mentioned above worked, but it was an unnecessary hurdle

**Comment by ranjancse26** [comment]
Unable to deploy the worker app. Tried with login too. However, the deploy is taking the user to https://localhost:8976/oauth/callback

**Comment by penalosa** [comment]
> Unable to deploy the worker app. Tried with login too. However, the deploy is taking the user to https://localhost:8976/oauth/callback

@ranjancse26 could you open a new issue with more details, and we can help debug further?

**Comment by ranjancse26** [comment]
> > Unable to deploy the worker app. Tried with login too. However, the deploy is taking the user to https://localhost:8976/oauth/callback
> 
> @ranjancse26 could you open a new issue with more details, and we can help debug further?

Here you go

https://github.com/cloudflare/workers-sdk/issues/5542
