### ISSUE TITLE
🐛 BUG: URLs in Durable Objects can't use https:// in pages dev

### ISSUE THREAD

**Issue by zegevlier** [cloudflare/wrangler2#2639]
### Which Cloudflare product(s) does this pertain to?

Pages, Workers/Other, Wrangler

### What version of `Wrangler` are you using?

0.0.0-6f0f2ba6

### What operating system are you using?

Windows

### Describe the Bug

Take the following function:

```ts
interface Env {
    HELLO_DURABLE: DurableObjectNamespace;
}

export const onRequestGet = async (context) => {
    const id = context.env.HELLO_DURABLE.newUniqueId();
    const stub = context.env.HELLO_DURABLE.get(id);

    // This code does work:
    const response = await stub.fetch("http://do.fake/");
    // This code does not work:
    // const response = await stub.fetch("https://do.fake/");

    const text = await response.text();
    return new Response(text);
}
```

I would expect both of these lines to work, but the second one results in the following error:
```
[pages:err] GET /pages_durable: TypeError: fetch failed
    at Object.processResponse (C:\Users\zegevlier\AppData\Local\npm-cache\_npx\dce38835dbc726fc\node_modules\undici\lib\fetch\index.js:199:23)
    at C:\Users\zegevlier\AppData\Local\npm-cache\_npx\dce38835dbc726fc\node_modules\undici\lib\fetch\index.js:928:38
    at node:internal/process/task_queues:140:7
    at AsyncResource.runInAsyncScope (node:async_hooks:204:9)
    at AsyncResource.runMicrotask (node:internal/process/task_queues:137:8)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
[pages:err] Cause: Error: B02E0000:error:0A00010B:SSL routines:ssl3_get_record:wrong version number:c:\ws\deps\openssl\openssl\ssl\record\ssl3_record.c:355:
```

There is a simple workaround here, just setting the protocol to `http`, but it would be nice for both of them to work.

I have a minimal reproduction [here](https://github.com/zegevlier/pages-do-minimal).
You can run it with `npx wrangler@beta pages dev .\dist\ --do HELLO_DURABLE=HelloDurable@pages-do-minimal` in the pages folder, and `npx wrangler@beta dev --local --persist` in the worker folder.
Then, `http://127.0.0.1:8788/pages_durable` works with the `http` version, and doesn't with the `https` version.

**Comment by CarmenPopoviciu** [comment]
hi @zegevlier thank you for reporting this issue. Are you still experiencing this problem with latest wrangler version?

**Comment by zegevlier** [comment]
Hey @CarmenPopoviciu I provided a minimal reproduction in the original issue. I can't test it myself at the moment, but feel free to give that a try!

**Comment by CarmenPopoviciu** [comment]
ah my apologies, I totally missed that. I will have a look and follow-up here

**Comment by CarmenPopoviciu** [comment]
picking this up as part of the ongoing work on https://github.com/cloudflare/workers-sdk/milestone/10

**Comment by CarmenPopoviciu** [comment]
hi @zegevlier 

I had a look at your repro repository (thank you so much for putting that together ❤ ) and it doesn't seem like this is an issue anymore. I'm seeing for both `const response = await stub.fetch("http://do.fake");` and `const response = await stub.fetch("https://do.fake");`

![Image](https://github.com/cloudflare/workers-sdk/assets/4638332/8a0a40a2-6969-4fbe-981a-26e89cc31584)

Unless I'm doing something wrong, it would seem the issue was fixed in a recent wrangler version (I tested with latest wrangler version `3.62.0`). Therefore closing, but pls do re-open if you're still experiencing issues on your side

<3
