### ISSUE TITLE
🐛 BUG: Using `--test-scheduled` leads to `Cannot read properties of undefined (reading 'middleware')` 

### ISSUE THREAD

**Issue by JustinBeckwith** [cloudflare/wrangler2#2666]
### Which Cloudflare product(s) does this pertain to?

D1, Workers/Other, Wrangler

### What version of `Wrangler` are you using?

2.8.0

### What operating system are you using?

Mac

### Describe the Bug

I am trying to run my esm based worker using a scheduled job.  I am using D1 with a local database.  I'm running:

```
wrangler dev --local --test-scheduled
```

I have a pretty basic `index.ts` that handles both `fetch` and `scheduled`, with the scheduled bit looking like:

```js
async scheduled(event: ScheduledEvent, env: Env, ctx: ExecutionContext) {
	ctx.waitUntil(run());
},
```

My `wrangler.toml` looks like:

```toml
name = "bagelbot"
main = "src/index.ts"
compatibility_date = "2023-01-19"
kv_namespaces = [
  { binding = "profiles", id = "703d9a3a402f4011b6017bbe647322db", preview_id = "d0d0fe7f498b4582a9a41b880b1898fd" }
]

[[ d1_databases ]]
binding = "DB" # i.e. available in your Worker on env.DB
database_name = "bagelbot"
database_id = "534f88ea-cbbd-4d1b-b8b7-e663c8cc10a2"

[triggers]
crons = ["*/5 * * * *"] # every 5 minutes
```

I get the following output:

```
Delegating to locally-installed wrangler@2.8.0 over global wrangler@2.8.0...
Run `npx wrangler dev --local --test-scheduled` to use the local version directly.

 ⛅️ wrangler 2.8.0 (update available 2.9.0)
-----------------------------------------------------
Want to try out the next version of local mode using the open-source Workers runtime?
Switch out --local for --experimental-local and let us know what you think at https://discord.gg/cloudflaredev !
▲ [WARNING] Processing wrangler.toml configuration:

    - D1 Bindings are currently in alpha to allow the API to evolve before general availability.
      Please report any issues to https://github.com/cloudflare/wrangler2/issues/new/choose
      Note: Run this command with the environment variable NO_D1_WARNING=true to hide this message
  
      For example: `export NO_D1_WARNING=true && wrangler <YOUR COMMAND HERE>`


Using vars defined in .dev.vars
Your worker has access to the following bindings:
- KV Namespaces:
  - profiles: d0d0fe7f498b4582a9a41b880b1898fd
- D1 Databases:
  - DB: bagelbot (local)
- Vars:
  - DISCORD_CLIENT_ID: "(hidden)"
  - DISCORD_PUBLIC_KEY: "(hidden)"
  - DISCORD_BOT_TOKEN: "(hidden)"
  - DISCORD_INTRO_CHANNEL_ID: "(hidden)"
  - DISCORD_THREAD_CHANNEL_ID: "(hidden)"
⎔ Starting a local server...
╭─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮
│ [b] open a browser, [d] open Devtools, [l] turn off local mode, [c] clear console, [x] to exit                                                                                                                  │
╰─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
Debugger listening on ws://127.0.0.1:57177/927d862e-17d3-4edb-9c6c-8726737c10f5
For help, see: https://nodejs.org/en/docs/inspector
Debugger attached.
[NPXI] better-sqlite3 not available locally. Attempting to use npx to install temporarily.
[mf:inf] Updated `Request.cf` object cache!
[NPXI] Installing... (npx --prefer-offline -y -p better-sqlite3@7.6.2)
[NPXI] Installed into /Users/justin.beckwith/.npm/_npx/485d09d313c7e301/node_modules.
[NPXI] To skip this step in future, run: npm install --save-dev better-sqlite3@7.6.2
[mf:err] TypeError: Cannot read properties of undefined (reading 'middleware')
    at /private/var/folders/5s/5qx4kx9n4f3d_ktmjm4rqgsr0000gq/T/tmp-12172-qiLpsBYJ9LmL/middleware-insertion-facade.js:7:17
    at SourceTextModule.evaluate (node:internal/vm/module:226:23)
    at VMScriptRunner.runAsModule (/Users/justin.beckwith/Code/bagelbot/node_modules/@miniflare/runner-vm/src/index.ts:38:18)
    at VMScriptRunner.run (/Users/justin.beckwith/Code/bagelbot/node_modules/@miniflare/runner-vm/src/index.ts:82:17)
    at Miniflare.#reload (/Users/justin.beckwith/Code/bagelbot/node_modules/@miniflare/core/src/index.ts:775:13)
    at Miniflare.getPlugins (/Users/justin.beckwith/Code/bagelbot/node_modules/@miniflare/core/src/index.ts:1017:5)
    at createServer (/Users/justin.beckwith/Code/bagelbot/node_modules/@miniflare/http-server/src/index.ts:369:19)
    at startServer (/Users/justin.beckwith/Code/bagelbot/node_modules/@miniflare/http-server/src/index.ts:476:18)
    at main (file:///Users/justin.beckwith/Code/bagelbot/node_modules/wrangler/miniflare-dist/index.mjs:6283:22)
    at file:///Users/justin.beckwith/Code/bagelbot/node_modules/wrangler/miniflare-dist/index.mjs:6351:1
TypeError: Cannot read properties of undefined (reading 'middleware')
    at /private/var/folders/5s/5qx4kx9n4f3d_ktmjm4rqgsr0000gq/T/tmp-12172-qiLpsBYJ9LmL/middleware-insertion-facade.js:7:17
    at SourceTextModule.evaluate (node:internal/vm/module:226:23)
    at VMScriptRunner.runAsModule (/Users/justin.beckwith/Code/bagelbot/node_modules/@miniflare/runner-vm/src/index.ts:38:18)
    at VMScriptRunner.run (/Users/justin.beckwith/Code/bagelbot/node_modules/@miniflare/runner-vm/src/index.ts:82:17)
    at Miniflare.#reload (/Users/justin.beckwith/Code/bagelbot/node_modules/@miniflare/core/src/index.ts:775:13)
    at Miniflare.getPlugins (/Users/justin.beckwith/Code/bagelbot/node_modules/@miniflare/core/src/index.ts:1017:5)
    at createServer (/Users/justin.beckwith/Code/bagelbot/node_modules/@miniflare/http-server/src/index.ts:369:19)
    at startServer (/Users/justin.beckwith/Code/bagelbot/node_modules/@miniflare/http-server/src/index.ts:476:18)
    at main (file:///Users/justin.beckwith/Code/bagelbot/node_modules/wrangler/miniflare-dist/index.mjs:6283:22)
    at file:///Users/justin.beckwith/Code/bagelbot/node_modules/wrangler/miniflare-dist/index.mjs:6351:1
Waiting for the debugger to disconnect...
```

**Comment by rozenmd** [comment]
Thanks for reporting @JustinBeckwith, and sorry you've run into this issue - we'll have a fix rolled out shortly

**Comment by hanzlahabib** [comment]
facing same issue, thanks for the report..

**Comment by rozenmd** [comment]
@hanzlahabib this has been fixed in the latest version of wrangler, can you run `npm install wrangler@latest`?
