### ISSUE TITLE
Error when running ctrl-c in dev mode

### ISSUE THREAD

**Issue by Electroid** [cloudflare/wrangler2#375]
### What version of `Wrangler` are you using?

0.0.0-b8e3b01 (alpha)

### What operating system are you using?

Mac

### Describe the Bug

The following error occurs when running `ctrl-c` when `wrangler dev` is active. Sometimes the errors appears, but sometimes it does not.

```
Warning: Can't perform a React state update on an unmounted component. This is a no-op, but it indicates a memory leak in your application. To fix, cancel all subscriptions and asynchronous tasks in a useEffect cleanup function.
    at Remote (/.../node_modules/wrangler/wrangler-dist/cli.js:113212:42)
    at Dev (/.../node_modules/wrangler/wrangler-dist/cli.js:113160:13)
    at ErrorBoundary2 (/.../node_modules/wrangler/wrangler-dist/cli.js:92101:39)
    at withErrorBoundary(Dev)
    at App (/.../node_modules/wrangler/wrangler-dist/cli.js:76011:9)
```

**Comment by threepointone** [comment]
I'll assign this to myself, I understand what's going on here and the fix is a bit involved.

**Comment by threepointone** [comment]
Unassigning myself, anyone else can take this if they'd like, or I can come back to it later
