### ISSUE TITLE
🐛 BUG: Early termination throws Warning: Can't perform a React state update on an unmounted component.

### ISSUE THREAD

**Issue by jgentes** [cloudflare/wrangler2#385]
### What version of `Wrangler` are you using?

0.0.0-aacd1c2

### What operating system are you using?

Ubuntu 20 (WSL)

### Describe the Bug

Start `wrangler dev index.ts` then immediately after `⬣ Listening at http://localhost:8787` appears, CTRL-C to break out. This error appears:
```
Warning: Can't perform a React state update on an unmounted component. This is a no-op, but it indicates a memory leak in your application. To fix, cancel all subscriptions and asynchronous tasks in a useEffect cleanup function.
    at Remote (/home/jgentes/.nvm/versions/node/v16.13.2/lib/node_modules/wrangler/wrangler-dist/cli.js:117133:42)
    at Dev (/home/jgentes/.nvm/versions/node/v16.13.2/lib/node_modules/wrangler/wrangler-dist/cli.js:117081:13)
    at ErrorBoundary2 (/home/jgentes/.nvm/versions/node/v16.13.2/lib/node_modules/wrangler/wrangler-dist/cli.js:95934:39)
    at withErrorBoundary(Dev)
    at App (/home/jgentes/.nvm/versions/node/v16.13.2/lib/node_modules/wrangler/wrangler-dist/cli.js:78296:9)

**Comment by Electroid** [comment]
Thanks for reporting! Looks like we're already tracking in #375

**Comment by jgentes** [comment]
Ah, I forgot the first rule of submitting an issue :)
