### ISSUE TITLE
Global install `npm i wrangler@beta -g` fails

### ISSUE THREAD

**Issue by jgentes** [cloudflare/wrangler2#42]
This is in WSL2 while logged in as root:
* Ubuntu: 20.04
* Node: 16.13.0

```
 ~ - [] # npm i wrangler@beta -g
npm ERR! code 1
npm ERR! path /root/.nvm/versions/node/v16.13.0/lib/node_modules/wrangler/node_modules/esbuild
npm ERR! command failed
npm ERR! command sh -c node install.js
npm ERR! internal/modules/cjs/loader.js:638
npm ERR!     throw err;
npm ERR!     ^
npm ERR!
npm ERR! Error: Cannot find module '/root/.nvm/versions/node/v16.13.0/lib/node_modules/wrangler/node_modules/esbuild/install.js'
npm ERR!     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
npm ERR!     at Function.Module._load (internal/modules/cjs/loader.js:562:25)
npm ERR!     at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
npm ERR!     at startup (internal/bootstrap/node.js:283:19)
npm ERR!     at bootstrapNodeJSCore (internal/bootstrap/node.js:623:3)
```

Note that installing without `-g` and using `npx wrangler` works fine :)

**Comment by jgentes** [comment]
Fixed by downloading a new Ubuntu WSL image and following the install instructions for Node here: https://docs.microsoft.com/en-us/windows/dev-environment/javascript/nodejs-on-wsl
