### ISSUE TITLE
🐛 BUG: PrismaClient is unable to be run in the browser.

### ISSUE THREAD

**Issue by willin** [cloudflare/wrangler2#451]
### What version of `Wrangler` are you using?

0.0.0-a73e32f

### What operating system are you using?

Mac

### Describe the Bug

a bit like: https://github.com/remix-run/remix/issues/667

```
Error: PrismaClient is unable to be run in the browser.
In case this error is unexpected for you, please report it in https://github.com/prisma/prisma/issues
    at new PrismaClient2 (/Users/v0/Sites/remix-init/node_modules/.prisma/client/index-browser.js:107:11)
    at loader (/Users/v0/Sites/remix-init/build/route-module:/Users/v0/Sites/remix-init/app/root.tsx:26:18)
    at callRouteLoader (/Users/v0/Sites/remix-init/node_modules/@remix-run/server-runtime/esm/data.js:69:20)
    at /Users/v0/Sites/remix-init/node_modules/@remix-run/server-runtime/esm/server.js:266:108
    at Array.map (<anonymous>)
    at renderDocumentRequest (/Users/v0/Sites/remix-init/node_modules/@remix-run/server-runtime/esm/server.js:266:67)
    at requestHandler (/Users/v0/Sites/remix-init/node_modules/@remix-run/server-runtime/esm/server.js:51:26)
    at /Users/v0/Sites/remix-init/node_modules/@remix-run/cloudflare-pages/esm/worker.js:22:12
    at handleFetch (/Users/v0/Sites/remix-init/node_modules/@remix-run/cloudflare-pages/esm/worker.js:49:24)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

**Comment by mcfadyeni** [comment]
I was experiencing this issue as well. This isn't wrangler2 specific, you have to alias `prisma` using `require`.

Example for `esbuild`, using `@esbuild-plugins/node-modules-polyfill`:
```javascript
...
plugins: [
    alias({
        '@prisma/client': require.resolve('@prisma/client'),
    }),
]
...
```
The full example repo can be found here: https://github.com/vinaypuppal/cfw-prisma-template

**Comment by willin** [comment]
Cloudflare pages not workers.

no wrangler.toml and no webpack

**Comment by willin** [comment]
build.js works, however i don't how to config it


```
===============================================================================
Remix-0  | Watching Remix app in development mode...
Remix-0  | 💿 Built in 169ms
Tailwind CSS-1  | warn - The `darkMode` option in your Tailwind CSS configuration is set to `false`, which now behaves the same as `media`.
Tailwind CSS-1  | warn - Change `darkMode` to `media` or remove it entirely.
Tailwind CSS-1  | warn - https://tailwindcss.com/docs/upgrade-guide#remove-dark-mode-configuration
Tailwind CSS-1  | warn - No utility classes were detected in your source files. If this is unexpected, double-check the `content` option in your Tailwind CSS configuration.
Tailwind CSS-1  | warn - https://tailwindcss.com/docs/content-configuration
Cloudflare Wrangler-2  | Compiling worker to "/var/folders/td/zr87rwn546n4q0y3zddn95zw0000gn/T/functionsWorker.js"...
Cloudflare Wrangler-2  | ✘ [ERROR] Could not resolve "fs"
Cloudflare Wrangler-2  |     node_modules/@esbuild-plugins/node-modules-polyfill/dist/index.js:17:37:
Cloudflare Wrangler-2  |       17 │ const fs_1 = __importDefault(require("fs"));
Cloudflare Wrangler-2  |          ╵                                      ~~~~
Cloudflare Wrangler-2  |   The package "fs" wasn't found on the file system but is built into node. Are you trying to bundle for node? You can use "platform: 'node'" to do that, which will remove this error.
Cloudflare Wrangler-2  | ✘ [ERROR] Could not resolve "path"
Cloudflare Wrangler-2  |     node_modules/@esbuild-plugins/node-modules-polyfill/dist/index.js:18:39:
Cloudflare Wrangler-2  |       18 │ const path_1 = __importDefault(require("path"));
Cloudflare Wrangler-2  |          ╵                                        ~~~~~~
Cloudflare Wrangler-2  |   The package "path" wasn't found on the file system but is built into node. Are you trying to bundle for node? You can use "platform: 'node'" to do that, which will remove this error.
Cloudflare Wrangler-2  | ✘ [ERROR] Could not resolve "fs"
Cloudflare Wrangler-2  |     node_modules/esbuild/lib/main.js:1693:17:
Cloudflare Wrangler-2  |       1693 │ var fs = require("fs");
Cloudflare Wrangler-2  |            ╵                  ~~~~
Cloudflare Wrangler-2  |   The package "fs" wasn't found on the file system but is built into node. Are you trying to bundle for node? You can use "platform: 'node'" to do that, which will remove this error.
Cloudflare Wrangler-2  | ✘ [ERROR] Could not resolve "os"
Cloudflare Wrangler-2  |     node_modules/esbuild/lib/main.js:1694:17:
Cloudflare Wrangler-2  |       1694 │ var os = require("os");
Cloudflare Wrangler-2  |            ╵                  ~~~~
Cloudflare Wrangler-2  |   The package "os" wasn't found on the file system but is built into node. Are you trying to bundle for node? You can use "platform: 'node'" to do that, which will remove this error.
Cloudflare Wrangler-2  | ✘ [ERROR] Could not resolve "path"
Cloudflare Wrangler-2  |     node_modules/esbuild/lib/main.js:1695:19:
Cloudflare Wrangler-2  |       1695 │ var path = require("path");
Cloudflare Wrangler-2  |            ╵                    ~~~~~~
Cloudflare Wrangler-2  |   The package "path" wasn't found on the file system but is built into node. Are you trying to bundle for node? You can use "platform: 'node'" to do that, which will remove this error.
Cloudflare Wrangler-2  | ✘ [ERROR] Could not resolve "child_process"
Cloudflare Wrangler-2  |     node_modules/esbuild/lib/main.js:1834:28:
Cloudflare Wrangler-2  |       1834 │ var child_process = require("child_process");
Cloudflare Wrangler-2  |            ╵                             ~~~~~~~~~~~~~~~
Cloudflare Wrangler-2  |   The package "child_process" wasn't found on the file system but is built into node. Are you trying to bundle for node? You can use "platform: 'node'" to do that, which will remove this error.
Cloudflare Wrangler-2  | ✘ [ERROR] Could not resolve "crypto"
Cloudflare Wrangler-2  |     node_modules/esbuild/lib/main.js:1835:21:
Cloudflare Wrangler-2  |       1835 │ var crypto = require("crypto");
Cloudflare Wrangler-2  |            ╵                      ~~~~~~~~
Cloudflare Wrangler-2  |   The package "crypto" wasn't found on the file system but is built into node. Are you trying to bundle for node? You can use "platform: 'node'" to do that, which will remove this error.
Cloudflare Wrangler-2  | ✘ [ERROR] Could not resolve "tty"
Cloudflare Wrangler-2  |     node_modules/esbuild/lib/main.js:1839:18:
Cloudflare Wrangler-2  |       1839 │ var tty = require("tty");
Cloudflare Wrangler-2  |            ╵                   ~~~~~
Cloudflare Wrangler-2  |   The package "tty" wasn't found on the file system but is built into node. Are you trying to bundle for node? You can use "platform: 'node'" to do that, which will remove this error.
Cloudflare Wrangler-2  | 8 error(s) and 0 warning(s) when compiling Worker.
Cloudflare Wrangler-2  | Build failed with 8 errors:
Cloudflare Wrangler-2  | node_modules/@esbuild-plugins/node-modules-polyfill/dist/index.js:17:37: ERROR: Could not resolve "fs"
Cloudflare Wrangler-2  | node_modules/@esbuild-plugins/node-modules-polyfill/dist/index.js:18:39: ERROR: Could not resolve "path"
Cloudflare Wrangler-2  | node_modules/esbuild/lib/main.js:1693:17: ERROR: Could not resolve "fs"
Cloudflare Wrangler-2  | node_modules/esbuild/lib/main.js:1694:17: ERROR: Could not resolve "os"
Cloudflare Wrangler-2  | node_modules/esbuild/lib/main.js:1695:19: ERROR: Could not resolve "path"
Cloudflare Wrangler-2  | ...
Cloudflare Wrangler-2  | If you think this is a bug then please create an issue at https://github.com/cloudflare/wrangler2/issues/new.
```

**Comment by mcfadyeni** [comment]
Unfortunately Remix does not allow you to hook into the compiler (using `esbuild` under the hood) so adding the necessary polyfills and alias will not be possible. This is not a problem with wrangler2.

**Comment by sidharthachatterjee** [comment]
Hey there. Thanks for opening this. It seems like this is an issue with Remix not allowing you to configure polyfills for these imports. Since this isn't an issue with `wrangler`, I'll go ahead and close this for the moment. 

Happy to help with any other questions. Thanks!
