### ISSUE TITLE
Improve error message when login fails

### ISSUE THREAD

**Issue by Electroid** [cloudflare/wrangler2#539]
We should improve the error message when there's a fatal error during login:

```
SyntaxError: Unexpected token < in JSON at position 0
    at JSON.parse (<anonymous>)
    at Response2.json (/node_modules/wrangler/wrangler-dist/cli.js:104161:21)
    at async exchangeRefreshTokenForAccessToken (/node_modules/wrangler/wrangler-dist/cli.js:133913:11)
    at async refreshToken (/node_modules/wrangler/wrangler-dist/cli.js:134131:23)
    at async loginOrRefreshIfRequired (/node_modules/wrangler/wrangler-dist/cli.js:134050:12)
    at async Object.handler (/node_modules/wrangler/wrangler-dist/cli.js:143181:24)
Did not login, quitting...
```

**Comment by caass** [comment]
This could be because the error message being returned to us is HTML, so we should probably try parsing as HTML (or at least saying more nicely "there was an error") if JSON parsing fails or we get a 500 response, etc.
