### ISSUE TITLE
🐛 BUG: Wrangler tail fails with "Cannot use 'in' operator to search for 'cron' in null

### ISSUE THREAD

**Issue by vlovich** [cloudflare/wrangler2#918]
### What version of `Wrangler` are you using?

0.0.30

### What operating system are you using?

Linux

### Describe the Bug

Tail died with
```
node_modules/wrangler/wrangler-dist/cli.js:200
```
then showing a large amount of minified code (> 1kb) starting with:
```
Check the render method of %s.`,Ye(su.type)||"Unknown"));var _e=kt(Y,
```
then:
```
TypeError: Cannot use 'in' operator to search for 'cron' in null
    at xqe (/home/vlovich/cloudflare/blob-gateway-worker/node_modules/wrangler/wrangler-dist/cli.js:558:1156)
    at _i.GG (/home/vlovich/cloudflare/blob-gateway-worker/node_modules/wrangler/wrangler-dist/cli.js:558:580)
    at _i.emit (node:events:527:28)
    at B9.d9e (/home/vlovich/cloudflare/blob-gateway-worker/node_modules/wrangler/wrangler-dist/cli.js:324:59955)
    at B9.emit (node:events:527:28)
    at B9.dataMessage (/home/vlovich/cloudflare/blob-gateway-worker/node_modules/wrangler/wrangler-dist/cli.js:324:39151)
    at B9.getData (/home/vlovich/cloudflare/blob-gateway-worker/node_modules/wrangler/wrangler-dist/cli.js:324:38466)
    at B9.startLoop (/home/vlovich/cloudflare/blob-gateway-worker/node_modules/wrangler/wrangler-dist/cli.js:324:35220)
    at B9._write (/home/vlovich/cloudflare/blob-gateway-worker/node_modules/wrangler/wrangler-dist/cli.js:324:34573)
    at writeOrBuffer (node:internal/streams/writable:390:12)

Node.js v17.6.0
```

**Comment by petebacondarwin** [comment]
That will be from this line of code:

https://github.com/cloudflare/wrangler2/blob/0a79d75e6aba11a3f0d5a7490f1b75c9f3e80ea8/packages/wrangler/src/tail/printing.ts#L46

**Comment by petebacondarwin** [comment]
Looks like the `event` in the eventMessage was `null`. Is this expected? If so, we need to make the Wrangler code more tolerant here.
