### ISSUE TITLE
🐛 BUG: Cannot find module 'node:child_process'

### ISSUE THREAD

**Issue by mikeRead** [cloudflare/wrangler2#979]
### What version of `Wrangler` are you using?

0.0.0-58ce471

### What operating system are you using?

Windows

### Describe the Bug

Not really sure if im missing anything but I havn't had any issues with wrangler v1 but no mater what I do on v2 I aways get a "Cannot find module 'node:child_process'" error

Tested on node versions: 12.18, 13.6, 14.15.4, 16.6 (via NVM)
I also tried installing both wrangler and wrangler@beta
All comands had Admin permissions too

```
$npm install -g npx
$npm install wrangler --save-dev
$npx wrangler init my-worker
[[Throws The Error here]]
```

```
$npm install -g wrangler 
$wrangler init my-worker
[[Throws The Error here]]
```
```
$npm install -g wrangler 
$wrangler -v
[[Throws The Error here]]
```

The Error:
```
internal/modules/cjs/loader.js:969
  throw err;
  ^

Error: Cannot find module 'node:child_process'
Require stack:
- C:\Repos\cfApi\file-move\node_modules\wrangler\bin\wrangler.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:966:15)
    at Function.Module._load (internal/modules/cjs/loader.js:842:27)
    at Module.require (internal/modules/cjs/loader.js:1026:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (C:\Repos\cfApi\file-move\node_modules\wrangler\bin\wrangler.js:2:19)
    at Module._compile (internal/modules/cjs/loader.js:1138:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1158:10)
    at Module.load (internal/modules/cjs/loader.js:986:32)
    at Function.Module._load (internal/modules/cjs/loader.js:879:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    'C:\\...REMOVED...\\node_modules\\wrangler\\bin\\wrangler.js'
  ]
}
```

Also per readme flow:
https://6b05b6e1.cloudflare-docs-7ou.pages.dev/workers/wrangler/getting-started/
```
npx wrangler@beta dev index.js
Cannot find module 'node:child_process'
Require stack:
- C:\...REMOVED..\AppData\Roaming\npm-cache\_npx\44796\node_modules\wrangler\bin\wrangler.js
```

**Comment by threepointone** [comment]
I'm sorry you had to face this experience. Our minimum version is 16.7, which introduced the `node:` prefix for builtin modules. It looks like the error we throw when we detect an unsupported version isn't working correctly, and I'll fix that asap.

**Comment by mikeRead** [comment]
No worries and thanks for the quick reply 16.7 worked as expected.
